### ISSUE TITLE
Administrator Role Missing under Users Info

### ISSUE THREAD

**Issue by startupweb** [strangerstudios/pmpro-roles#19]
Hello,

I'm not sure but it seems like the Administrator Role disappears when I install this plugin.

When I disabled the plugin, then the Administrator role appears again.

Is that supposed to happen?

https://imgur.com/a/LM9nm1J

Thanks,
   wiL

**Comment by andrewlimaza** [comment]
Thanks for the feedback Wil, we have just patched this. You may download the 'dev' branch for the pre-release. We are going to test this further and release it as soon as we possibly can.

**Comment by startupweb** [comment]
Thank you, it's fixed.
