### ISSUE TITLE
Selling membership with WooCommerce, overrides PMPro role with it's default.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-roles#22]
**Describe the bug**

When using WooCommerce to sell Memberships, Woo's role overrides Membership Level.

**To Reproduce**
Set up a Level, should take on "new-level" role.
Set up product in Woo to sell Membership.
Buy Membership.

**Comment by andrewlimaza** [comment]
This has been fixed and merge, you can get a pre-release by grabbing the 'dev' branch. Update to come out soon.
