### ISSUE TITLE
Creating a new level without checking the option to create a custom role does not create a draft of that membership level role

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-roles#23]
**Describe the bug**
After activation of this add on, roles are auto created for old levels. However, when creating a new level, if the checkbox to create a custom role for this new level is not checked, the level after creation does not get a custom role. There should be a draft role created upon creating this level, that the site owner is able to go back to select and assign to their new level, but this is not there. 

The workaround is to use a third party user role plugin such as this to create a new role which can then be assigned to that new level created via its Edit Level settings page.

**To Reproduce**
1. Activate 'PMPro Roles'
2. Click to 'add a new membership level' and do not check the box to "create a custom role for that level"
3. Save and exit, go back to the edit level settings page, scroll to the Roles section, you would not see the custom role drafted or created, except that checkbox in `step 2` was checked

**Expected behavior**
Even if the checkbox in step 2 is not checked, a custom role should be created as a draft for that new level created

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress V5.7, PMPro Roles V1.3.2
```
</details>

**Comment by andrewlimaza** [comment]
Fixed in latest commit, update going out shortly.
