### ISSUE TITLE
Old Role Staying After Membership Checkout

### ISSUE THREAD

**Issue by FindomApp** [strangerstudios/pmpro-roles#32]
Hi, I have been using this plugin for a few months, and it has been working great. When someone registers on my wordpress website for free, they are assigned the user role "Subscriber" automatically. Then, when they go through the membership checkout with PMPro, up until now there role would then be changed from subscriber --> customer. I took about a month off from the project, and I just came back tonight and ran some tests, and for some reason now, when a member checks out, their role does change to customer like it should, but it also continues to list them as "subscriber." I do not want this to happen, because I am using the BP Better messages plugin, and I am trying to restrict "subscribers" from sending private messages and only allow "customers" to send private message. I'm not sure what happened, but now that it's keeping the "subscriber" role for new paying members, and so members are now paying but they still can't send private messages because "subscriber" roles are blocked from doing so.

So, is there any way to switch things back to the way they were about a month ago? So this way when someone goes through a membership checkout, their new role is implemented and their old role is deleted? Let me know if this is possible and/or what the options are. Thank you!

**Comment by andrewlimaza** [comment]
Hey @FindomApp 

Please can you open a ticket on https://www.paidmembershipspro.com/support so we may assist you further. We don't crawl our Github repo's for support related queries.

This sounds like a greater issue vs being a Roles Add On specific issue.

To backdate to an older version you should be able to grab it here - https://github.com/strangerstudios/pmpro-roles/releases

**Comment by FindomApp** [comment]
Okay thank you!
