### ISSUE TITLE
Warning: Undefined array key 

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-roles#48]
**Describe the bug**
When you save a level, a Warning Message appears:

**To Reproduce**
1. install roles add on
2. Click to save level
3. Warning appears.
4. But plugin works correctly.

**Screenshots**

<img width="980" alt="Screenshot 2024-07-01 at 11 22 36 AM" src="https://github.com/strangerstudios/pmpro-roles/assets/8083630/dc198947-a707-4d13-a6ca-5d7d2df7da42">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
PMPro 3.0.5
WP 6.5.5
Roles Add On v1.4.2
PHP 8.2.19 and PHP 8.1.23 
</details>

**Comment by TheRayJohnson** [comment]
I'm also seeing this error when saving a role. It's causing me to unable to save a [Yearly payment plan term](https://github.com/strangerstudios/pmpro-payment-plans), it just defaults to `$x.xx due Now.`

`Notice: Undefined index: edit in /public_html/wp-content/plugins/pmpro-roles/pmpro-roles.php on line 143`

**Comment by andrewlimaza** [comment]
@TheRayJohnson This PR may fix it - https://github.com/strangerstudios/pmpro-roles/pull/42

I plan on retesting it soon.

**Comment by andrewlimaza** [comment]
@TheRayJohnson can confirm this won't interfere with saving the Payment Plan. The warning should not affect functionality whatsoever, maybe something else is interfering.

You can reach out to our support if you still need help resolving this - https://www.paidmembershipspro.com/support/

**Comment by andrewlimaza** [comment]
I can confirm the latest dev branch also resolves this warning and should go out in the near future. Closing this issue for now.
