### ISSUE TITLE
Addon overwrites previous user roles instead of adding a user role

### ISSUE THREAD

**Issue by andreasputlitz** [strangerstudios/pmpro-roles#7]
Hi! I have been asked by support to put my recommendation here.

So far, when assigning a user role, the addon deletes any user role that has been assigned to the user previously.

The desired behaviour would be that it leaves any other role previously assigned untouched, and only adds/removes its user role(s) to/from the existing user roles.

Cheers!

**Comment by kimcoleman** [comment]
This issue is similar to the one here which is an approved improvement. We will continue to discuss and work through the issue here: https://github.com/strangerstudios/pmpro-roles/issues/6
